### ISSUE TITLE
HomeAssistant

### ISSUE THREAD

**Issue by deathly1987** [NilsRo/ImpulseSmartMeter#1]
Hi,

hab alles eingerichtet und kann die Werte über MQTT Explorer auch auslesen, aber ich bekomm die Daten nicht in HomeAssistant integriert.
Habe es schon versucht über configuration.yaml manuell einzubinden, aber irgendwas mache ich falsch.

Hast du vielleicht einen Tipp?

Danke

**Comment by NilsRo** [comment]
Leider nicht, ich nutze die Anbindung mit NodeRed. Aber dann scheint es ja generell schonmal zu funktionieren. Wenn es eine besondere Eigenheit zu berücksichtigen gibt sag gerne bescheid, hab HomeAssistent aber nicht selber im Einsatz.

**Comment by deathly1987** [comment]
Wie liest du die Daten im NodeRed aus?
Das habe ich auch auf HA installiert und könnte bei Bedarf damit arbeiten.

**Comment by NilsRo** [comment]
Dort gibt es ein MQTT Reader auf alle Topics, den leite ich einmal ungefiltert in eine Influx und ansonsten auf Webservices für einen Homeserver weiter. Ist ganz einfach, brauchst nur noch einen Mosquitto für die Verteilung. Den solltest ja aber auch haben.

**Comment by deathly1987** [comment]
Hab es doch noch in HomeAssistant eingebunden bekommen.
Allerdings probiere ich gerade es per ESP direkt in HomeAssistant zu betreiben, aber allerdings passt von den Settings irgendwas nicht, also der Reedkontakt reagiert nicht.

```
packages:
  base: !include common/base.yaml
  base_global: !include common/base_global.yaml

substitutions:
  device_name: gasmeter
  device_name_short: gasmeter
  friendly_name: "Gas Meter"
  esp_type: "ESP32"
  impulsfactor_gas: "0.01"
  update_interval: 300s
  update_interval_sensor: 10s

esphome:
  name: "gaszaehler"
  friendly_name: Gaszähler

esp32:
  board: mhetesp32miniki
  framework:
    version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: total_pulses_gas
    type: int
    restore_value: false
    initial_value: '0'

binary_sensor:
  - platform: gpio
    id: internal_pulse_counter_gas
    pin: GPIO27
    internal: true
    filters:
      - delayed_on: 100ms
    on_press:
      then:
        - lambda: id(total_pulses_gas) += 1;

sensor:
  - platform: template
    name: "Gas used"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
    update_interval: ${update_interval_sensor}
    lambda: |-
        return id(total_pulses_gas) * ${impulsfactor_gas};
```

Der Fehler muss mit der Angabe des Boards liegen.
Habe genau das selbe für die Wasseruhr mit einem D1 Mini laufen.

Vielleicht hast du ja hierzu ein Tipp.

Danke schön
